### ISSUE TITLE
Feature Request: Guix Package

### ISSUE THREAD

**Issue by jgarte** [russell/sphinxcontrib-cldomain#19] opened 2022-12-30 08:09 UTC
https://todo.sr.ht/~whereiseveryone/guixrus/1124

**Comment by svetlyak40wt** [comment] 2022-12-30 08:31
By the way, I've moved from Sphinx and reStructured to my own [documentation builder](https://40ants.com/doc/) which is more suitable for Common Lisp projects. I've took only one Sphinx feature – it's JavaScript search.

**Comment by russell** [comment] 2022-12-30 10:02
Alexander Artemenko ***@***.***> writes:

> By the way, I've moved from Sphinx and reStructured to my own
> [documentation builder](https://40ants.com/doc/) which is more
> suitable for Common Lisp projects. I've took only one Sphinx feature –
> it's JavaScript search.

Awesome, I'm glad to hear that you have found a solution for your
documentation.  Documentation for lots of Common Lisp projects is pretty
bad and it makes Common Lisp difficult for newcomers.  I'm happy to see
more inovation in this space.

I'm still maintaining this project, and it's by no means depricated.

**Comment by russell** [comment] 2022-12-30 10:03
jgart ***@***.***> writes:

> https://todo.sr.ht/~whereiseveryone/guixrus/1124

This project has been moved to source-hut,
https://sr.ht/~rsl/sphinxcontrib-cldomain/ I'm sorry I haven't completed
the migration, I've been pretty busy, but I will delete these github
repositories soon.

We should continue discussing the creation of these guix packages on
your todo item.

**Comment by svetlyak40wt** [comment] 2022-12-30 10:44
Probably it is better to archive repository and to leave in the README.md a link to a new place where the project can be found instead of just deleting the repository. This way, your projects at a new place will have some traffic from GitHub.

**Comment by svetlyak40wt** [comment] 2022-12-30 10:47
@russell by the way, I'm just wondering, why did you decide to switch to Source Hut?

**Comment by russell** [comment] 2022-12-30 11:36
Alexander Artemenko ***@***.***> writes:

> Probably it is better to archive repository and to leave in the
> README.md a link to a new place where the project can be found instead
> of just deleting the repository. This way, your projects at a new
> place will have some traffic from GitHub.

Yeah, not being sure how to best deprecate this location is part of the
issue.  I was considering setting it as a mirror, but I also don't like
the idea of leaving my code there.  I think I'll create a new readme to
redirect people.

> @russell by the way, I'm just wondering, why did you decide to switch
> to Source Hut?

It's multifaceted, ideologically I don't agree with the Copilot data
harvesting.  So it's partly that.

I really don't like Github actions, For example if I want to test a new
build script on Source Hut, i can submit the YAML directly.  This makes
the cycle time much lower when testing my CI pipeline.  Github actions
also encourages users to split their pipeline up into isolated steps,
which are commonly separate repositories in github.  These are then
supposed to be discovered/sold via their marketplace (read, walled
garden).  Github actions has to be one of the most frustrating ways to
automate project related tasks, mostly because the execution environment
is not reproducible on a local machine. Instead, i believe that being
able to run everything locally is most important, and that having a way
to automate this on a remote system is the secondary concern.  Gtihub
has this the other way around, and it's just plain bad.

Further more, Github seems totally committed to trying to extend it's
cloud product line, so this means they are trying to find new github
controlled solutions for things like security scanning, and even code
editing.  They are going to continue to build out their forge as a means
to commercialise their other product lines.  By being on the platform,
I'm encouraging this.

The forking model.  I don't think it's bad, but it's very messy, if i
look at my personal profile, have over a hundred projects since i want
to contribute upstream, i can't make them private and still submit a PR,
i can't delete them in bulk.  So I'm not sure that it's always reducing
the burden to contribute since I have to manually delete all the repos
after i have my changes accepted.  The forking model also forces users
to join the forge to contribute.  When reviewing forks, often users just
keep slapping new commits over the top, in the end pressing the "Merge"
button is resigning yourself to an attitude of not caring about the
commit history of your project.

The notifications are shitty, my work email account receives hundreds of
emails a day from github, and there is now way to reliably filter them.
This is a combination of the issues with modern email services like
GMail being unable to filter based on headers, and also having no option
other than subscribed or not.  We have bots, submitting PR's created via
github actions to bump gems/npm packages, spamming PR's.  I see this as
them wanting me on the website, using the website, they recently updated
their file browser, it's becoming more and more like an electron app, i
believe they are going to keep going until the website is essentially a
vscode plugin.

So as a result, I'm going to remove all projects from Github.  I would
rather have a conversation via email, rather than having to use a
website.  Sure submitting patches via email requires additional local
setup, but iterating on a PR is not a great experience either.  So I
would say it's a different amount of effort rather than more or less
effort.  Git started out as a decentralised system, github is an attempt
to centralise this.  I'm not sure if you remember sourceforge, but it
was heralded as the opensource forge for a long time, now it has
horrible ergonomics and was loaded up with ads to make it profitable.  I
don't want to ride out this wave with Github, in the long run I would
rather self host, but in the meantime Source Hut seems like a nice place
for the next few years.  The only drawback i can see is it might make my
projects less discover-able, but TBH finding projects on Github is not
easy anymore because of how big it is.

BTW, I also looked at the common-lisp.net gitlab, but that forge also
seems bloated and slow, so I'm not convinced by it either.  Though i
respect community effort to keep that site running.

**Comment by russell** [comment] 2023-01-18 20:11
this project is moving here, please continue this on the mailing list https://sr.ht/~rsl/sphinxcontrib-cldomain/

**Closed by russell** 2023-01-18 20:11 UTC
